[versions]
tuweni = "2.3.1"
log4j= "2.23.1"
vertex= "4.5.9"
besuInternal = "24.7.0"
tekuInternal =  "24.8.0"
picocli = "4.6.1"
netty = "4.1.110.Final"
discovery = "24.6.0"
oshi = "6.6.2"
assertj = "3.26.0"
mockito = "5.12.0"
lombok = "1.18.34"
jupiter = "5.8.1"
rocksdbjni = "8.3.2"
prometheus = "0.16.0"

[libraries]
tuweni-bytes = { module = "org.apache.tuweni:tuweni-bytes", version.ref = "tuweni"}
tuweni-crypto = { module = "org.apache.tuweni:tuweni-crypto", version.ref = "tuweni"}
tuweni-rlp = { module = "org.apache.tuweni:tuweni-rlp", version.ref = "tuweni"}
tuweni-ssz = { module = "org.apache.tuweni:tuweni-ssz", version.ref = "tuweni"}

log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j"}
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j"}

vertx-core= { module = "io.vertx:vertx-core", version.ref = "vertex"}
vertx-web= { module = "io.vertx:vertx-web", version.ref = "vertex"}

besu-internal-metrics-core= { module = "org.hyperledger.besu.internal:metrics-core", version.ref = "besuInternal"}
besu-internal-core = { module = "org.hyperledger.besu.internal:core", version.ref = "besuInternal"}
besu-internal-config = { module = "org.hyperledger.besu.internal:config", version.ref = "besuInternal"}
besu-internal-plugin-api = { module = "org.hyperledger.besu:plugin-api", version.ref = "besuInternal"}

teku-internal-infrastructure-events = { module = "tech.pegasys.teku.internal:infrastructure-events", version.ref = "tekuInternal"}
teku-internal-async = { module = "tech.pegasys.teku.internal:async", version.ref = "tekuInternal"}
teku-internal-infrastructure-restapi = { module = "tech.pegasys.teku.internal:infrastructure-restapi", version.ref = "tekuInternal"}
teku-internal-serviceutils = { module = "tech.pegasys.teku.internal:serviceutils", version.ref = "tekuInternal"}

teku-internal-io = { module = "tech.pegasys.teku.internal:io", version.ref = "tekuInternal"}
teku-internal-ssz = { module = "tech.pegasys.teku.internal:ssz", version.ref = "tekuInternal"}
teku-internal-unsigned = { module = "tech.pegasys.teku.internal:unsigned", version.ref = "tekuInternal"}
teku-internal-http = { module = "tech.pegasys.teku.internal:http", version.ref = "tekuInternal"}
teku-internal-json = { module = "tech.pegasys.teku.internal:json", version.ref = "tekuInternal"}

picocli = { module = "info.picocli:picocli", version.ref = "picocli"}
netty-all = { module = "io.netty:netty-all", version.ref = "netty"}
discovery = { module = "tech.pegasys.discovery:discovery", version.ref = "discovery"}
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi"}
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj"}
mockito-core= { module = "org.mockito:mockito-core", version.ref = "picocli"}
projectlombok= { module = "org.projectlombok:lombok", version.ref = "lombok"}

junit-jupiter-api= { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter"}
junit-jupiter-engine= { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter"}

rocksdbjni= { module = "org.rocksdb:rocksdbjni", version.ref = "rocksdbjni"}
prometheus-simpleclient= { module = "io.prometheus:simpleclient", version.ref = "prometheus"}


